# Generated by Django 3.0.5 on 2020-08-31 12:27

import car.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='car_db',
            fields=[
                ('car_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('car_make', models.CharField(max_length=100, verbose_name='Make (Toyota,Subaru,...)')),
                ('car_model', models.CharField(max_length=100, verbose_name='Model (Harrier...)')),
                ('car_color', models.CharField(max_length=100)),
                ('car_year', models.DateTimeField(blank=True, null=True, verbose_name='Year (mm/dd/2020)')),
                ('car_price', models.IntegerField(verbose_name='Price (Ksh)')),
                ('car_loc', models.CharField(max_length=100, verbose_name='Location ')),
                ('car_fuel', models.CharField(max_length=20, verbose_name='Fuel (Petrol,Diesel)')),
                ('condition_type', models.CharField(max_length=20, verbose_name='Condition Type (Used,international Used,New)')),
                ('car_mileage', models.IntegerField(verbose_name='Mileage')),
                ('car_transmission', models.CharField(max_length=20, verbose_name='Transmission (Auto, Manual,Semi)')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('image_front', models.ImageField(default='cardef.png', upload_to='front_pics')),
                ('image_side', models.ImageField(default='cardef.png', upload_to='side_pics')),
                ('image_back', models.ImageField(default='cardef.png', upload_to='back_pics')),
                ('image_full', models.ImageField(default='cardef.png', upload_to='full_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_placed', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True, validators=[car.models.future], verbose_name='Viewing Date (mm/dd/2020)')),
                ('order_email', models.EmailField(max_length=254, null=True, verbose_name='Confirm order Email')),
                ('order_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Confirm order Mobile')),
                ('car_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car_db')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
