# Generated by Django 3.0.5 on 2020-08-31 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car_db'),
        ),
    ]
