# Generated by Django 3.0.5 on 2020-09-02 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0003_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car_db', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
    ]
