# Generated by Django 3.0.5 on 2020-09-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20200902_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
