# Generated by Django 3.0.5 on 2020-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20200902_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_db',
        ),
        migrations.AddField(
            model_name='order',
            name='car_db',
            field=models.ManyToManyField(to='car.car_db', verbose_name='car'),
        ),
    ]
