# Generated by Django 3.0.5 on 2020-09-05 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20200905_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_db',
        ),
        migrations.AddField(
            model_name='order',
            name='car_db',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car_db', verbose_name='car'),
        ),
    ]
