# Generated by Django 3.0.5 on 2020-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20200905_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
