# Generated by Django 3.0.5 on 2020-09-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processed', 'processed')], default='pending', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
