# Generated by Django 3.0.5 on 2020-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20200914_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed.'), ('Closed', 'Closed')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
